### PR TITLE
Refactor for php 8

### PR DESCRIPTION
**Pull request by dstrop**
hi i would like to continue using this project in PHP 8
can we update the composer php requirement to `^8.0`

#### What does this PR do?
set required PHP version to `^8.0`
update `phpunit/phpunit` to `^9.3`

#### Checklist
- [x] Pull request contains a clear definition of changes
- [x] Tests (either unit, integration, or acceptance) written and passing
- [x] Relevant documentation produced and/or updated

### CODE REVIEW

**Comment by arron0** [comment]
@chadicus Hi would it be possible to merge this Pull request? It would be very helpful :-)

**Comment by chadicus** [comment]
@arron0 i'll try to get this in today.

**Review by chadicus — APPROVED** [review]

**Comment by chadicus** [comment]
@dstrop @arron0 This code is now available in v2.0.0

**Comment by arron0** [comment]
Thaks a lot :-) Big appreciation :-)

**Pull request merged**
